config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:password], controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root :to => 'homes#top'

  # homes
  get '/about' => 'homes#about'

  # tasks
  resources :tasks, only: [:index, :new, :create, :edit, :update] do
  collection do
      get 'search'
    end
  end
  delete 'tasks/:id' => 'tasks#destroy'
  get '/task_complete' => 'tasks#complete'
  get '/today' => 'tasks#today'

  # users
  get '/user' => 'users#show'
  get '/user/edit' => 'users#edit'
  patch 'user' => 'users#update'
  get '/user/quit_check' => 'users#quit_check'
  patch '/user/withdraw' => 'users#withdraw'



end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user

  has_one_attached :image

  enum status: { waiting: 0, started: 1, completed: 2 }

  validate :start_limit_check

	def start_limit_check
    errors.add(:limit, "は開始より日付を入力してください") if self.start && self.limit && self.start > self.limit
	end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/本.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "limit", "name", "note", "present", "start", "status", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob", "user"]
  end

  validates :name, presence: true
  validates :status, presence: true
  validates :present, presence: true
  validates :start, presence: true


  validates :limit, presence: true


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def index
    @tasks = current_user.tasks.all.order(limit: :ASC).page(params[:page])
    @q = Task.ransack(params[:q])
  end

  def search
    @q = Task.ransack(params[:q])
    @task_array = @q.result(distinct: true).page(params[:page]).order(limit: :ASC)
    @task_searches = @task_array.select{|hoge|hoge[:user_id] == current_user.id}
  end

  def create
    @task = Task.new(tasks_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to edit_task_path(@task.id)
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
    unless @task.user == current_user
      redirect_to new_task_path
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(tasks_params)
      if @task.status == "completed"
        @task_today_counts = Task.where(limit: Date.today).where(status: [0, 1]).count
        render :complete
      else
        redirect_to edit_task_path
      end
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to today_path
  end

  def today
    @today = Date.today
    @task = current_user.tasks.where(limit: Date.today).where(status: [0, 1])
    @task_today_counts = @task.where(limit: Date.today).where(status: [0, 1]).count
    @limit_over_tasks = current_user.limit_over_tasks
  end

  def complete
    @task = current_user.tasks.find(task.id)
    @task_today_counts = current_user.tasks.where(limit: Date.today).where(status: [0, 1])
  end

  private

  def tasks_params
    params.require(:task).permit(:name, :start, :limit, :note, :present, :status, :image)
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/complete.html.erb
<h2 class="headline">タスク達成！</h2>

<div class="container">
  <% if  @task_today_counts == 0 %>
    <div clss="picuture">
      <%= image_tag "社長.jpg", size: '300x300' %>
    </div>

    <div class="complete_item">
      タスクの完了お疲れさまでした！<br />
      ご褒美の獲得おめでとうございます！<br />
      <span class="marker">今日はこれだけ！</span>あとはゆっくり過ごしましょ〜
    </div>

    <div class="complete_task">
      <table class="complete_task">
        <tr>
          <td class="present">獲得ご褒美</td>
          <td class="present"><%= @task.present %></td>
        </tr>
      </table>
    </div>



  <% else %>
    <div clss="picuture">
      <%= image_tag "丸.jpg", size: '300x300' %>
    </div>

      <div class="complete_item">
        タスクの完了お疲れさまでした！<br />
        ご褒美の獲得おめでとうございます！<br />
        今日のタスクは<span class="marker">あと<%= @task_today_counts %>個</span>です。もう少し頑張りましょう！
      </div>
      <div class="complete">
        <table border="complete_task">
          <tr>
            <td class="present">獲得ご褒美</td>
            <td class="present"><%= @task.present %></td>
          </tr>
        </table>
      </div>
  <% end %>

   <div class="action">
    <%= link_to "ホームへ戻る", today_path %>
  </div>

</div>

app/views/tasks/edit.html.erb
<h2 class="headline">タスク編集</h2>

<div class="container">
  <div class="error">
    <% if @task.errors.any? %>
      <h2 class="error_message">
        <%= @task.errors.count %>件のエラーが発生しました。
      </h2>

        <div class="errors">
          <ul>
            <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  </div>

  <%= form_with model: @task do |f| %>

  <table class="edit_task">
    <tr>
      <td class="width20">タスク名</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_name"></label>
          <%= f.text_field :name, class: "text_string" %>
        </div>
      </td>
    </tr>
    <tr>
      <td class="width20">ステータス</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_status"></label>
          <%= f.select :status, Task.statuses_i18n.invert.to_a %>
        </div>
      </td>
    </tr>
    <tr>
      <td class="width20">開始</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_start"></label>
          <%= f.date_field :start %>
        </div>
      </td>
    </tr>
    <tr>
      <td class="width20">期限</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_limit"></label>
          <%= f.date_field :limit %>
        </div>
      </td>
    </tr>

    <tr>
      <td class="width20">ご褒美</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_present"></label>
          <%= f.text_field :present, class: "text_string" %>
        </div>
      </td>
    </tr>

    <tr>
      <td class="width20">メモ</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_present"></label>
            <%= f.text_area :note, class: "text_note" %>
        </div class="form-group">
        <div>
          <%= image_tag @task.get_image(500,500), width:'90%' %>
        </div>
        <%= f.file_field :image, accept: "image/*" %>
      </td>
    </tr>

  </table>

  <div class="form-group">
    <%= f.submit "変更を保存", class: "btn btn-info" %>
    <%= link_to "削除", task_path(@task.id), method: :delete, "data-confirm" => "削除しますか？", class:"btn btn-danger" %>

  </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<h2 class="headline">タスク一覧</h2>

<div class="container">
    <div class="search">
      <%= search_form_for @q, url: search_tasks_path do |f| %>
        <%= f.search_field :name_cont, placeholder: '検索ワード', required: true %>
        <%= f.select :status_eq_any, Task.statuses.keys.map.with_index { |k, i| [t("enums.task.status.#{k}"), i] } %>
        <%= f.submit '検索', class: 'btn btn-info' %>
      <% end %>
  </div>

  <table class="index_task">

    <thead>
      <tr>
        <th class="width30">ステータス</th>
        <th class="width30">タスク名</th>
        <th class="width30">ご褒美</th>
        <th class="width30">開始</th>
        <th class="width30">期限</th>
      </tr>
    </thead>

  <% @tasks.each do |task| %>
    <tbody>
      <tr>
        <td><%= task.status_i18n %></td>
        <td><%= link_to task.name, edit_task_path(task) %></td>
        <td><%= task.present %></td>
        <td><%= task.start %></td>
        <td><%= task.limit %></td>
      </tr>
    </tbody>
  <% end %>
  </table>
  <div class="pagenation_tag">
    <%= paginate @tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<h2 class="headline">タスク追加</h2>

<div class="container">
  <div class="error">
    <% if @task.errors.any? %>
    <h2 class="error_message">
      <%= @task.errors.count %>件のエラーが発生しました。
    </h2>

      <div class="errors">
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  </div>

  <%= form_with model: @task do |f| %>

  <table clas="new_task">
    <tr>
      <td class="width20">タスク名</td>
      <td class="width80">
        <div class="form-group">
          <label for="task_name"></label>
          <%= f.text_field :name, class: "text_string" %>
        </div>
      </td>
    </tr>
    <tr align='center'>
      <td class="width20">開始</td>
      <td class="width80">
        <div class="form-group">
          <label for="start"></label>
          <%= f.date_field :start, class:"order-date-form", min: Date.current %>
        </div>
      </td>
    </tr>
    <tr align='center'>
      <td class="width20">期限</td>
      <td class="width80">
        <div class="form-group">
          <label for="limit"></label>
          <%= f.date_field :limit, class:"order-date-form", min: Date.current %>
        </div>
      </td>
    </tr>
    <tr align='center'>
      <td class="width20">ご褒美</td>
      <td class="width80">
        <div class="form-group">
          <label for="present"></label>
          <%= f.text_field :present, class: "text_string" %>
        </div>
      </td>
    </tr>
    <tr align='center'>
      <td class="width20">メモ</td>
      <td class="width80">
        <div class="form-group">
          <label for="note"></label>
          <%= f.text_area :note, class: "text_note" %><br />
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </td>
    </tr>
  </table>

  <div class="field">
    <%= f.submit "タスク追加", class: "btn btn-info" %>
  </div>

  <% end %>
</div>

app/views/tasks/search.html.erb
<div class="container">
  <h2 class="headline">検索結果</h2>
    <table class="search_task">
      <% if @task_searches.present? %>
      <% search_word = @q.name_cont %>
      <% search_status = @q.status_eq_any.enum_for %>

    <h4 class="search_word">タスク名"<%= search_word %>"、ステータス"<%= @task_searches.first.status_i18n %>" </h4>
      <thead>
        <tr>
          <th>ステータス</th>
          <th>タスク名</th>
          <th>期日</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @task_searches.each do |task_search| %>
          <td><%= task_search.status_i18n %></td>
          <td><%= link_to task_search.name, edit_task_path(task_search.id) %></td>
          <td><%= task_search.limit %></td>
        </tr>
        <% end %>
      <% else %>
        <h3 class="nothing">検索結果がありません。</h3>
      <% end %>
    </table>
</div>

app/views/tasks/today.html.erb
<h2 class="headlin">TODAY</h2>
<div class="container">
    <h3 class="user_name"><%= current_user.name %>さん</h3>
      <p class="today_item">
        お疲れさまです。<br />
        今日（<%= l @today, format: :short %>）のタスクは<span class="marker">( <%= @task_today_counts %> )件</span>です。今日はこれだけ頑張りましょう！
      </p>
      <div class="tasks_today">
        <table class="tasks">
          <tr>
            <th class="width30">ステータス</th>
            <th class="width30">タスク名</th>
            <th class="width30">ご褒美</th>
          </tr>
          <% @task.each do |task| %>
            <tr>
              <td><%= task.status_i18n %></td>
              <td><%= link_to task.name, edit_task_path(task.id) %></td>
              <td><%= task.present %></td>
            </tr>
           <% end %>
        </table>
      </div>

      <div class="notcompleted_task_introduce">
        未完了タスクがございます。。。ご確認ください！m(_ _)m
      </div>
      <div class="tasks_nocompleted">
        <table class="tasks">
          <tr>
            <th class="width30">ステータス</th>
            <th class="width30">タスク名</th>
            <th class="width30">期日</th>
          </tr>
          <% @limit_over_tasks.each do |limit_over_task| %>
            <tr align="center">
              <td><%= limit_over_task.status_i18n %></td>
              <td><%= link_to limit_over_task.name, edit_task_path(limit_over_task.id) %></td>
              <td><%= limit_over_task.limit %></td>
            </tr>
          <% end %>
        </table>
      </div>


      <p class="action">
        <%= link_to "全てのタスクを確認するー＞", tasks_path %>
      </p>

</div>