config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:password], controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root :to => 'homes#top'

  # homes
  get '/about' => 'homes#about'

  # tasks
  resources :tasks, only: [:index, :new, :create, :edit, :update] do
  collection do
      get 'search'
    end
  end
  delete 'tasks/:id' => 'tasks#destroy'
  get '/task_complete' => 'tasks#complete'
  get '/today' => 'tasks#today'

  # users
  get '/user' => 'users#show'
  get '/user/edit' => 'users#edit'
  patch 'user' => 'users#update'
  get '/user/quit_check' => 'users#quit_check'
  patch '/user/withdraw' => 'users#withdraw'



end

app/models/user.rb
class User < ApplicationRecord

  has_many :tasks, dependent: :destroy
  has_many :limit_over_tasks, ->{where("`limit`<'#{Date.today}' and status!=2 ")},class_name: "Task"

  enum status: { waiting: 0, started: 1, completed: 2 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    today_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :is_deleted])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]

  def after_sign_in_path_for(resource)
    today_path
  end

  def after_sign_out_path_for(resouce)
    new_user_session_path
  end

  def user_state
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted==true)
        redirect_to new_user_registration_path
      end
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @task_today_counts = current_user.tasks.where(limit: Date.today, status: [0,1]).count
    if Rails.env.production?
      @task_achievement = current_user.tasks.where("DATE_FORMAT(start,'%Y') = ? AND DATE_FORMAT(start,'%m') = ?", Time.now.year.to_s, Time.now.month.to_s)
    else
      @task_achievement = current_user.tasks.where("strftime('%Y', start) = ? AND strftime('%m', start) = ?", Time.now.year.to_s, Time.now.month.to_s)
    end
      
    @task_achievement_ratio_original = @task_achievement.group("tasks.status").count("tasks.id").sort_by { |_, v| v }.reverse.to_h

    @task_achievement_ratio = {}
    @task_achievement_ratio_original.each do |k,v|
      achievement = (v.to_f / @task_achievement.count) * 100
      @task_achievement_ratio[Task.statuses_i18n[k]] = achievement.round
    end
  end

  def edit
    current_user
  end

  def update
    current_user.update(user_params)
    redirect_to user_path
  end

  def quit_check

  end

  def withdraw
    current_user.update(is_deleted: true)
    reset_session
    redirect_to new_user_registration_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="headline">ユーザー情報編集</h2>

<%= form_with model: current_user do |f| %>

<div class="container">
  <div class="form-group">ユーザー名：
    <label for="user_name"></label>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <div class="email">メールアドレス：
      <label for="email"></label>
      <%= f.text_field :email, autofocus: true, placeholder:"メールアドレス" %>
    </div>
  </div>

  <div class='quit_check'>
    ユーザーステータス：
    <%= link_to "退会する", user_quit_check_path, class:"btn btn-danger"%>
  </div>

  <div class="update">
    <%= f.submit "編集内容を保存", class: "btn btn-info" %>
  </div>


</div>




<% end %>

app/views/users/quit_check.html.erb
<h2>本当に退会しますか？</h2>

<div class='quit_check_item'>
  退会するとこのユーザーアカウントでのログインが出来なくなってしまいます。<br />
  退会する場合は、「退会する」をクリックしてください。
</div>

<div class="container">
  <div class="quit_check">
      <%= image_tag "お辞儀.jpg", size: "300x300" %>
      <%= link_to "退会しない", user_path, class: "btn btn-info" %>
      <%= link_to "退会する", user_withdraw_path, method: :patch, "data-confirm" => "退会しますか？",class:"btn btn-danger"%>
      <%= image_tag "お辞儀２.jpg", size: "300x300" %>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="headline">ユーザー情報</h3>

<div class="container">
  <div class="edit_user">
      <%= link_to "編集する", user_edit_path, class: "btn btn-info" %>
    </div>
  <table class="user">
    <tr>
      <td class="width30">ユーザー名</td>
      <td class="width70"><%= current_user.name %></td>
    </tr>
    <tr>
      <td class="width30">メールアドレス</td>
      <td class="width70"><%= current_user.email %></td>
    </tr>
    <tr>
      <td class="width30">
        今日はこれだけ<br />
        （残りタスク数）
      </td>
      <td class="width70"><%=  @task_today_counts %>件</td>
    </tr>
    <tr>
      <td class="width30">
        達成率<br />
        （１ヶ月）
      </td>
      <td class="width70"><%= pie_chart @task_achievement_ratio, donut: true, suffix: "%" %></td>
    </tr>
  </table>
</div>