config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:password], controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root :to => 'homes#top'

  # homes
  get '/about' => 'homes#about'

  # tasks
  resources :tasks, only: [:index, :new, :create, :edit, :update] do
  collection do
      get 'search'
    end
  end
  delete 'tasks/:id' => 'tasks#destroy'
  get '/task_complete' => 'tasks#complete'
  get '/today' => 'tasks#today'

  # users
  get '/user' => 'users#show'
  get '/user/edit' => 'users#edit'
  patch 'user' => 'users#update'
  get '/user/quit_check' => 'users#quit_check'
  patch '/user/withdraw' => 'users#withdraw'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>今日はこれだけ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light border-bottom">
        <% if user_signed_in? %>
          <div class="container">
            <%= link_to '今日はこれだけ', today_path,class:"navbar-brand" %>
            <ul class="navbar-nav ml-auto">
              <li class="item"><%= link_to "ホーム", today_path, class:"navbar-brand" %></li>
              <li class="item"><%= link_to "タスク一覧", tasks_path, class:"navbar-brand" %></li>
              <li class="item"><%= link_to "タスク追加", new_task_path, class:"navbar-brand" %></li>
              <li class="item"><%= link_to "ユーザー情報", user_path, class:"navbar-brand" %></li>
              <li class="item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"navbar-brand" %></li>
            </ul>
          </div>
        <% else %>
          <div class="container">
            <%= link_to '今日はこれだけ', root_path, class:"navbar-brand" %>
            <ul class="navbar-nav justify-content-end">
              <li class="item"><%= link_to "About", about_path,class:"navbar-brand" %></li>
              <li class="item"><%= link_to "ログイン", new_user_session_path,class:"navbar-brand" %></li>
              <li class="item"><%= link_to "新規登録", new_user_registration_path,class:"navbar-brand" %></li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>
    <%= yield %>

     

  </body>
</html>